#!/usr/bin/env python3
"""
Train YOLOv8-nano v6 on model-assisted labels.

Uses labels from labels_v6/ directory (generated by model-assisted-label.py).
Handles class imbalance by oversampling rare classes.

Usage:
    python3 perception/train-v6.py [--epochs 100] [--batch 16]
"""

import argparse
import os
import shutil
import random
from pathlib import Path
from collections import defaultdict

PROJ_DIR = Path(__file__).parent.parent
LABEL_DIR = PROJ_DIR / 'data' / 'labels_v6'

CLASS_NAMES = ['Zombie', 'Skeleton', 'Creeper', 'Spider', 'Slime',
               'Enderman', 'Witch', 'Cow', 'Pig', 'Sheep',
               'Chicken', 'Squid', 'Cod', 'Item', 'Villager']


def setup_dataset():
    """Build balanced YOLO dataset from model-assisted labels."""
    yolo_dir = PROJ_DIR / 'data' / 'yolo_v6'
    train_imgs = yolo_dir / 'train' / 'images'
    train_labels = yolo_dir / 'train' / 'labels'
    val_imgs = yolo_dir / 'val' / 'images'
    val_labels = yolo_dir / 'val' / 'labels'

    for d in [train_imgs, train_labels, val_imgs, val_labels]:
        if d.exists():
            shutil.rmtree(d)
        d.mkdir(parents=True)

    # Categorize frames by which classes they contain
    pairs = []
    class_frames = defaultdict(list)

    for img_path in sorted(LABEL_DIR.glob('*.jpg')):
        label_path = img_path.with_suffix('.txt')
        if not label_path.exists():
            continue

        content = label_path.read_text().strip()
        if not content:
            pairs.append((img_path, label_path, set(), False))
            continue

        classes_in_frame = set()
        for line in content.split('\n'):
            if line.strip():
                cls = int(line.split()[0])
                classes_in_frame.add(cls)
                class_frames[cls].append(len(pairs))

        pairs.append((img_path, label_path, classes_in_frame, True))

    print(f"Total pairs: {len(pairs)}")
    entity_pairs = [p for p in pairs if p[3]]
    empty_pairs = [p for p in pairs if not p[3]]
    print(f"  With entities: {len(entity_pairs)}")
    print(f"  Empty: {len(empty_pairs)}")

    print(f"\nClass distribution:")
    for cls_id, indices in sorted(class_frames.items()):
        print(f"  {CLASS_NAMES[cls_id]}: {len(indices)} frames")

    # Include all entity frames + limited empties
    max_empty = min(len(empty_pairs), len(entity_pairs) // 3)
    random.shuffle(empty_pairs)
    selected = entity_pairs + empty_pairs[:max_empty]
    random.shuffle(selected)

    # 85/15 split
    split = int(len(selected) * 0.85)
    train_set = selected[:split]
    val_set = selected[split:]

    for pair_list, img_dir, lbl_dir in [
        (train_set, train_imgs, train_labels),
        (val_set, val_imgs, val_labels),
    ]:
        for img_path, label_path, _, _ in pair_list:
            shutil.copy2(str(img_path), str(img_dir / img_path.name))
            shutil.copy2(str(label_path), str(lbl_dir / label_path.name))

    print(f"\nDataset: {len(train_set)} train, {len(val_set)} val")

    yaml_content = f"""path: {yolo_dir.resolve()}
train: train/images
val: val/images

nc: {len(CLASS_NAMES)}
names: {CLASS_NAMES}
"""
    yaml_path = yolo_dir / 'dataset.yaml'
    yaml_path.write_text(yaml_content)
    return str(yaml_path)


def train(yaml_path, epochs=100, batch=16):
    from ultralytics import YOLO

    print(f"\n=== Training YOLOv8-nano v6 (model-assisted labels) ===")
    print(f"Epochs: {epochs}, Batch: {batch}")

    yolo = YOLO('yolov8n.pt')
    results = yolo.train(
        data=yaml_path,
        epochs=epochs,
        batch=batch,
        imgsz=640,
        device='mps',
        workers=2,
        patience=20,
        save=True,
        project=str(PROJ_DIR / 'runs' / 'detect'),
        name='mc_entities_v6',
        exist_ok=True,
        # Augmentation
        hsv_h=0.015,
        hsv_s=0.5,
        hsv_v=0.3,
        degrees=5.0,
        translate=0.1,
        scale=0.3,
        flipud=0.0,
        fliplr=0.5,
        mosaic=0.8,
    )

    print(f"\n=== Training complete ===")
    best_path = PROJ_DIR / 'runs' / 'detect' / 'mc_entities_v6' / 'weights' / 'best.pt'
    print(f"Best model: {best_path}")

    # Validate
    best = YOLO(str(best_path))
    metrics = best.val(data=yaml_path)
    print(f"mAP50: {metrics.box.map50:.3f}")
    print(f"mAP50-95: {metrics.box.map:.3f}")

    return results


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--epochs', type=int, default=100)
    parser.add_argument('--batch', type=int, default=16)
    parser.add_argument('--setup-only', action='store_true')
    args = parser.parse_args()

    yaml_path = setup_dataset()
    if not args.setup_only:
        train(yaml_path, args.epochs, args.batch)


if __name__ == '__main__':
    main()
